name: openapi
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  expire_cache: ^2.0.1
  http: '>=0.13.0 <0.14.0'
  intl: '^0.17.0'
  meta: '^1.7.0'
  tuple: ^2.0.0
  uuid: ^3.0.5
  pointycastle: ^3.5.1
  convert: ^3.0.1
  test: ^1.20.1

dev_dependencies:
  lints: ^1.0.0
